# Generated by Django 4.0.5 on 2022-07-26 15:31

from django.db import migrations, models
import django.db.models.deletion
import jop.models


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0004_jop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jop',
            name='image',
            field=models.ImageField(upload_to=jop.models.image_upload),
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=100)),
                ('website', models.URLField()),
                ('cv', models.FileField(upload_to='apply/')),
                ('cover_letter', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('jop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_jop', to='jop.jop')),
            ],
        ),
    ]
