# Generated by Django 4.0.5 on 2022-07-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0005_alter_jop_image_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='cover_letter',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='apply',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
