# Generated by Django 4.0.5 on 2022-08-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0007_jop_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.FileField(default=1, upload_to='category/'),
            preserve_default=False,
        ),
    ]
