# Generated by Django 4.0.5 on 2022-08-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0008_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jop',
            name='company',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jop',
            name='jop_location',
            field=models.CharField(choices=[('On-site', 'On-site'), ('Remote', 'Remote')], default='name', max_length=15),
            preserve_default=False,
        ),
    ]
