# Generated by Django 4.0.5 on 2022-07-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='word',
            name='name_ar',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
